In [1]:
import pandas as pd

df = pd.read_csv("train.csv")
df

Age  BMI  High Blood Pressure  Fasting Blood Glucose  HbA1c Level  \
0       63   27                    1                    158          6.5   
1       25   25                    0                     85          5.0   
2       21   28                    0                    155          5.8   
3       47   29                    0                    159          3.5   
4       53   29                    0                    126          5.8   
...    ...  ...                  ...                    ...          ...   
70699   62   27                    0                    160          4.0   
70700   35   31                    1                    140          6.0   
70701   56   31                    0                    160          5.7   
70702   37   21                    0                    159          6.5   
70703   14   18                    0                    160          6.5   

       Smoking  Diagnosis  
0            0          0  
1            0          0  
2            0          0  
3            1          0  
4            1          0  
...        ...        ...  
70699        0          0  
70700        1          0  
70701        0          1  
70702        0          0  
70703        0          0  

[70704 rows x 7 columns]

In [3]:
x = df[["Age", "BMI", "HbA1c Level", "Fasting Blood Glucose", "High Blood Pressure", "Smoking"]].to_numpy()
y = df["Diagnosis"].to_numpy()

print(x.shape, y.shape)

(70704, 6) (70704,)


In [4]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)

print(x_train.shape, y_train.shape)
print(x_test.shape, y_test.shape)

(53028, 6) (53028,)
(17676, 6) (17676,)


In [5]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

ss.fit(x_train)  #mean, std 계산 
x_train_scaled = ss.transform(x_train)
x_test_scaled = ss.transform(x_test)

In [6]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(x_train_scaled, y_train)

print(lr.predict(x_train_scaled))

[0 0 0 ... 0 0 0]


In [7]:
import numpy as np

proba = lr.predict_proba(x_train_scaled)   # 클래스별 확률값 반환
print(np.round(proba, decimals=3))

[[0.995 0.005]
 [0.966 0.034]
 [1.    0.   ]
 ...
 [0.989 0.011]
 [0.959 0.041]
 [0.991 0.009]]


In [127]:
print(lr.classes_)

[0 1]


In [8]:
print(lr.coef_, lr.intercept_)

[[1.07239161 0.5330709  2.26340543 1.30247483 0.16863272 0.09362497]] [-4.77496755]


In [9]:
decisions=lr.decision_function(x_train_scaled)
print(decisions)

[-5.33227416 -3.3463285  -7.97329129 ... -4.5382396  -3.14048339
 -4.66977102]


In [10]:
from scipy.special import expit 
print(expit(decisions))

[0.00480982 0.0340156  0.00034442 ... 0.0105791  0.0414679  0.00928735]


In [16]:
lr=LogisticRegression(C=20,max_iter=1000)
lr.fit(x_train_scaled, y_train)

# 학습데이터로 학습한 모델로 학습/테스트 데이터의 성능 평가
print("학습용 데이터셋:", lr.score(x_train_scaled, y_train))
print("시험용 데이터셋:",lr.score(x_test_scaled, y_test))

학습용 데이터셋: 0.9556649317341782
시험용 데이터셋: 0.9543448744059742


In [116]:
df2 = pd.read_csv('test.csv')
df2

Age  BMI  High Blood Pressure  Fasting Blood Glucose  HbA1c Level  \
0       51   20                    0                    159          6.2   
1       14   20                    0                    158          6.1   
2       38   27                    0                    200          5.8   
3       16   17                    0                    126          3.5   
4       80   31                    1                    100          4.8   
...    ...  ...                  ...                    ...          ...   
17671    8   23                    0                    126          5.7   
17672   43   27                    0                     80          5.8   
17673   11   20                    0                    160          5.8   
17674   24   27                    0                     90          5.8   
17675   66   35                    0                    300          6.6   

       Smoking  
0            1  
1            0  
2            0  
3            1  
4            0  
...        ...  
17671        0  
17672        0  
17673        0  
17674        0  
17675        1  

[17676 rows x 6 columns]

In [117]:
y_predicted = df2[["Age", "BMI", "HbA1c Level", "Fasting Blood Glucose", "High Blood Pressure"]].to_numpy()

print(y_predicted.shape)

(17676, 5)


In [118]:
ss.fit(y_predicted)
y_predict_scaled = ss.transform(y_predicted)

In [119]:
y_predict = lr.predict(y_predict_scaled)

df2["Diagnosis"] = y_predict
df2

Age  BMI  High Blood Pressure  Fasting Blood Glucose  HbA1c Level  \
0       51   20                    0                    159          6.2   
1       14   20                    0                    158          6.1   
2       38   27                    0                    200          5.8   
3       16   17                    0                    126          3.5   
4       80   31                    1                    100          4.8   
...    ...  ...                  ...                    ...          ...   
17671    8   23                    0                    126          5.7   
17672   43   27                    0                     80          5.8   
17673   11   20                    0                    160          5.8   
17674   24   27                    0                     90          5.8   
17675   66   35                    0                    300          6.6   

       Smoking  Diagnosis  
0            1          0  
1            0          0  
2            0          0  
3            1          0  
4            0          0  
...        ...        ...  
17671        0          0  
17672        0          0  
17673        0          0  
17674        0          0  
17675        1          1  

[17676 rows x 7 columns]

In [120]:
import pandas as pd
import numpy as np

f = pd.read_csv("submission.csv")

f.dropna(axis=1, inplace=True)

# 아래 "np.arange(0, df.shape[0], 1)" 부분을, 솜솜이가 만든 모델이 예측한 값으로 대체!
y_pred = y_predict 

f["Diagnosis"] = y_pred
f.to_csv("new_submission.csv", index=False)